
println("Ob) Elastic electron scattering: the high-energy Rutherford limit as an absolute check of the Dirac " *
        "partial-wave cross sections.")

setDefaults("print summary: open", "zzz-ParticleScattering.sum")
setDefaults("unit: energy", "eV")

grid = Radial.Grid(Radial.Grid(false), rnt = 4.0e-6, h = 5.0e-2, hp = 0.6e-2, rbox = 10.0)

if  true
    # Last visit:  17-Aug-2026
    # Last successful:  17-Aug-2026
    # THE PHYSICS BEING CHECKED, and why this is an absolute test rather than an internal one.
    #
    # At a large scattering angle the projectile turns through a small impact parameter, i.e. it probes the region well
    # inside the atomic electron cloud, where the potential it sees is the bare nuclear one, -Z/r. As the impact energy
    # grows, that region dominates ever more strongly, and the backward differential cross section must approach the
    # Rutherford result for the FULL nuclear charge,
    #
    #        d sigma / d Omega  ->  Z^2 / ( 16 E^2 sin^4(theta/2) )        [a.u.]
    #
    # which at theta = 180 deg is simply Z^2/(16 E^2). Nothing in the computation is fitted to this: the cross section
    # comes from Dirac phase shifts of BOTH spin-orbit partners in JAC's own DFS field, summed to convergence, whereas
    # the right-hand side is the textbook closed form. Their agreement therefore tests the absolute normalisation of the
    # amplitudes, the phase-shift convention and the partial-wave sum all at once -- which no internal consistency check
    # can do.
    #
    #   REPORT (e + He, Z = 2, theta = 180 deg):
    #
    #       E [eV]      DCS [a.u.]      Rutherford      ratio
    #        200        6.27004e-3      4.62787e-3      1.3548
    #        500        8.41094e-4      7.40460e-4      1.1359
    #       1000        1.97821e-4      1.85115e-4      1.0686
    #       2000        4.64068e-5      4.62787e-5      1.0028
    #
    #   The ratio falls monotonically towards unity and reaches 1.003 at 2 keV, i.e. the computed cross section joins the
    #   exact analytic limit to 0.3 %. The residual excess at the lower energies is physical, not numerical: screening,
    #   exchange and the finite size of the electron cloud all still matter there, and all of them raise the backward
    #   cross section above the bare-nucleus value.
    #
    #   NOTE, and it is a limitation of the GRID rather than of the physics: pushing to 4 keV on this grid takes the ratio
    #   back UP to 1.09. A 4 keV electron has a de Broglie wavelength short compared with the spacing this grid provides
    #   near the nucleus, so the phase shifts lose accuracy. Any use of this module above ~2 keV needs a finer grid, and
    #   Bsplines.checkGridRepresentation should be consulted first (cf. Rule 12 in CLAUDE.md).
    #
    #   What is NOT claimed here: agreement with a measured differential cross section. That comparison needs a tabulated
    #   reference -- the NIST Electron Elastic-Scattering Cross-Section Database (SRD 64), generated by ELSEPA, is the
    #   natural one -- and is left to a branch that can quote it.
    energies = [200.0, 500.0, 1000.0, 2000.0]
    println("\n  E [eV]      DCS [a.u.]        Rutherford        ratio")
    for  en in energies
        psSettings = ParticleScattering.Settings(ParticleScattering.Settings(),
                                                 impactEnergies = [en], polarThetas = [Float64(pi)], polarPhis = [0.0],
                                                 printBefore = false, epsPartialWave = 1.0e-7, maxL = 150)
        wc = Atomic.Computation(Atomic.Computation(), name="Rutherford limit", grid=grid,
                                nuclearModel    = Nuclear.Model(2.0),
                                initialConfigs  = [Configuration("1s^2")],
                                finalConfigs    = [Configuration("1s^2")],
                                processSettings = psSettings )
        wd    = perform(wc; output=true)
        event = wd["particle-scattering events:"][1]
        E     = event.impactEnergy                       # already in atomic units
        ruth  = 4.0 / (16 * E * E)                       # Z^2 / (16 E^2),  sin^4(90 deg) = 1
        dcs   = event.angular[1].dcs
        println("  ", rpad(en, 10), rpad(round(dcs, sigdigits=6), 18), rpad(round(ruth, sigdigits=6), 18),
                round(dcs/ruth, digits=4))
    end
    #
elseif  false
    # Last successful:  unknown ...
    #
end
#
setDefaults("print summary: close", "")
