
println("Cj) Apply & test the MultipolePolarizibility module with ASF from an internally generated multiplet.")

if  false
    # Last visit:  31-Jul-2026
    # Last successful:  unknown ... (see comparison-to-literature note below; date NOT set since the
    #   result does not yet match the known exact value -- Rule 7).
    # Branch a: hydrogen 1s static electric-dipole polarizability -- the one case with an EXACT, textbook
    #   comparison value (no fitted/measured uncertainty involved): alpha_0(H, 1s) = 4.5 a.u. exactly
    #   (e.g. Bethe & Salpeter, "Quantum Mechanics of One- and Two-Electron Atoms", or any standard
    #   perturbation-theory derivation via the exact H Green's function).
    #
    # The intermediate (perturber) ASF are NOT taken from an AtomicState.GreenExpansion/Green-function
    # box-discretization; instead, a local, approximate Green multiplet gMultiplet is generated directly
    # as a plain Atomic.Computation of energies & ASF only (no properties) for the opposite-parity np
    # configurations 2p, 3p, 4p, 5p -- exactly the physically relevant perturber levels for a 1s ground
    # state -- and handed to MultipolePolarizibility.Settings. The outcome now reports BOTH the Coulomb
    # and Babushkin gauge (as an EmProperty), NOT calibrated onto a common scale -- see module docstring.
    # NOT Radial.Grid(true): its box reaches 614 a.u., and Bsplines.checkGridRepresentation refuses it
    # for H 1s + np perturbers, n = 2..5 -- a box that is much TOO LARGE starves the fixed number of
    # B-splines exactly as badly as one too small (Rule 12). 129.0 a.u. is the box the guard itself
    # names for these subshells.
    grid = Radial.Grid(Radial.Grid(true); rbox = 129.0)
    nm   = Nuclear.Model(1., PointNucleus())

    wa1 = Atomic.Computation(Atomic.Computation(), name="H perturber multiplet (np, n=2..5)", grid=grid,
                            nuclearModel=nm, configs=[Configuration("2p"), Configuration("3p"), Configuration("4p"), Configuration("5p")])
    wb1 = perform(wa1; output=true)
    gMultiplet = wb1["multiplet:"]

    polSettings = MultipolePolarizibility.Settings(MultipolePolarizibility.Settings(), multipoles=[E1], gMultiplet=gMultiplet, printBefore=true)
    wa = Atomic.Computation(Atomic.Computation(), name="H(1s) static electric-dipole polarizability", grid=grid,
                            nuclearModel=nm,
                            configs=[Configuration("1s")],
                            propertySettings=[polSettings] )
    wb = perform(wa; output=true)
    outcome = wb["Polarizibility outcomes:"][1]
    println("\n>> computed alpha_0 = $(outcome.alpha0) a.u.   (exact literature value = 4.5 a.u.)")
    println(">> ratio computed/exact [Coulomb]   = $(outcome.alpha0.Coulomb/4.5)")
    println(">> ratio computed/exact [Babushkin] = $(outcome.alpha0.Babushkin/4.5)")
    #
elseif false
    # Last visit:  31-Jul-2026
    # Last successful:  unknown ... (exploratory: high-n perturbers are NOT physically accurate bound
    #   states at this grid/basis size -- see module docstring -- so no literature-comparison date applies).
    # Branch b: same H(1s) system as branch a, but with a MUCH larger perturber multiplet (np, n=2..45)
    #   generated by the SAME independent-Atomic.Computation approach. Beyond about n=5-6 these "np"
    #   ASF are no longer genuine, physically converged bound Rydberg states for the default grid/basis
    #   (nsL=62, nsS=63 B-splines, box out to ~614 a.u.) -- they are properly normalized, mutually
    #   orthogonal pseudo-states instead, providing a simple, explicit (if crude) discrete approximation
    #   to the true continuum's contribution to the polarizability sum. Every individual perturber's
    #   contribution -- physical or pseudo-state alike -- is tabulated in both the Coulomb and Babushkin
    #   gauge by MultipolePolarizibility.displayContributions, so the running approach of alpha_0 toward
    #   (or past) the exact 4.5 a.u. can be inspected directly, term by term. n=45 is a deliberate, tested
    #   practical ceiling for the DEFAULT grid: the running Babushkin sum plateaus completely between
    #   n~40 and n=45 (identical to 12 significant figures), confirming genuine convergence rather than
    #   an arbitrary cutoff -- while n=60 configs, tried first, overflow the basis outright (a hard
    #   BoundsError in Bsplines' hydrogenic seeding step, not just a loss of accuracy): nsL=62 only
    #   supports ~117 total kappa=+1 eigenstates after the boundary-condition truncation, too few for
    #   59 simultaneously-requested np levels.
    #
    #   IMPORTANT open discrepancy (31-Jul-2026, web literature check, moderate confidence -- primary
    #   source PDF could not be fetched directly, based on converging AI-summarized search snippets of
    #   "Contribution of Discrete and Continuum Wave Functions in the Ground State Polarizability of
    #   Hydrogen"): the TRUE discrete-bound-state-only sum for H(1s) is reported there as ~3.6 a.u.,
    #   i.e. ~80% of the exact 4.5 a.u. total (continuum ~20%). Our own converged Babushkin result here
    #   is only 2.278 a.u. (~51%) -- a large, currently UNEXPLAINED shortfall even against the literature
    #   BOUND-only figure, not just against the full 4.5 a.u. Two live hypotheses, neither yet checked:
    #   (i) the higher (still formally bound, negative-energy) np perturbers below n~14 are themselves
    #   already box-distorted enough to systematically lose dipole strength before ever crossing to
    #   positive energy; (ii) the threshold where this grid's spectrum turns positive is simply too low
    #   in n, truncating genuine bound-like strength that a larger box would still show as bound. Not
    #   yet investigated further -- flagged here rather than presented as a settled result.
    grid = Radial.Grid(true)
    nm   = Nuclear.Model(1., PointNucleus())
    nMaxHighN = 45

    # gridStopper = false IS THE POINT OF THIS BRANCH, not a way round an inconvenient guard.
    # Bsplines.checkGridRepresentation correctly reports that 80 of these 88 subshells are not physical bound
    # Rydberg states on this grid -- it asks for a box of about 4769 a.u., which no fixed B-spline basis can
    # carry -- and the branch's own text above says the same thing: beyond n ~ 5-6 these are deliberately
    # pseudo-states, a discrete stand-in for the continuum's contribution to the polarizability sum. So the
    # guard is RIGHT and the branch wants exactly what the guard is refusing; it must therefore say so
    # explicitly rather than be silently exempted.
    wa1 = Atomic.Computation(Atomic.Computation(), name="H perturber multiplet (np, n=2..$nMaxHighN)", grid=grid,
                            nuclearModel=nm, configs=[Configuration("$(n)p") for n = 2:nMaxHighN],
                            asfSettings=AsfSettings(AsfSettings(); gridStopper = false))
    wb1 = perform(wa1; output=true)
    gMultiplet = wb1["multiplet:"]

    polSettings = MultipolePolarizibility.Settings(MultipolePolarizibility.Settings(), multipoles=[E1], gMultiplet=gMultiplet, printBefore=true)
    wa = Atomic.Computation(Atomic.Computation(), name="H(1s) static electric-dipole polarizability, extended (pseudo-)perturber set",
                            grid=grid, nuclearModel=nm,
                            configs=[Configuration("1s")],
                            propertySettings=[polSettings] )
    wb = perform(wa; output=true)
    outcome = wb["Polarizibility outcomes:"][1]

    # Running (cumulative) alpha_0, ordered by ascending perturber energy (i.e. roughly ascending n),
    # to see explicitly how -- and how much -- the high-n/pseudo-continuum tail keeps adding to the sum.
    ordered  = sort(outcome.contributions, by = c -> c.nuLevel.energy)
    runningC = 0.0;   runningB = 0.0
    println("\n  Running sum of alpha_0 vs perturber (ordered by ascending energy):")
    println("  " * "-"^74)
    for  (i,c) in enumerate(ordered)
        global runningC = runningC + c.contribAlpha0.Coulomb;   global runningB = runningB + c.contribAlpha0.Babushkin
        if  i <= 35  ||  i % 10 == 0  ||  i == length(ordered)
            println("   perturber index=$i   energy=$(c.nuLevel.energy)   term contribAlpha0[Bab]=$(c.contribAlpha0.Babushkin)" *
                    "   running alpha_0 [Babushkin] = $runningB" )
        end
    end
    println("  " * "-"^74)

    println("\n>> computed alpha_0 = $(outcome.alpha0) a.u.   (exact literature value = 4.5 a.u.)")
    println(">> ratio computed/exact [Coulomb]   = $(outcome.alpha0.Coulomb/4.5)")
    println(">> ratio computed/exact [Babushkin] = $(outcome.alpha0.Babushkin/4.5)")
    #
elseif true
    # NOT Radial.Grid(true) here. Its box is 614 a.u. and Bsplines.checkGridRepresentation refuses it for
    # Li [He]2s + [He]np, n = 2..10 -- a box much TOO LARGE starves the fixed number of B-splines exactly as
    # badly as one too small (Rule 12). The guard names 359 a.u. as the box these subshells want, and the
    # EXPONENTIAL family cannot be tuned to it: its achievable r_max is quantised (151.4, 214.9, 304.9,
    # 432.7 ...), so no rbox request lands near 359. The non-exponential family honours rbox to 0.1 %.
    # hp = rbox/300 is the recipe Basics.recommendedGrid itself uses.
    grid = Radial.Grid(Radial.Grid(false), rnt = 4.0e-06, h = 5.0e-2, hp = 1.20, rbox = 359.0)
    nm   = Nuclear.Model(3., PointNucleus())
    nMaxLi = 10

    wa1 = Atomic.Computation(Atomic.Computation(), name="Li perturber multiplet ([He]np, n=2..$nMaxLi)", grid=grid,
                            nuclearModel=nm, configs=[Configuration("[He] $(n)p") for n = 2:nMaxLi])
    wb1 = perform(wa1; output=true)
    gMultiplet = wb1["multiplet:"]

    polSettings = MultipolePolarizibility.Settings(MultipolePolarizibility.Settings(), multipoles=[E1], gMultiplet=gMultiplet, printBefore=true)
    wa = Atomic.Computation(Atomic.Computation(), name="Li [He]2s static electric-dipole polarizability", grid=grid,
                            nuclearModel=nm,
                            configs=[Configuration("[He] 2s")],
                            propertySettings=[polSettings] )
    wb = perform(wa; output=true)
    outcome = wb["Polarizibility outcomes:"][1]

    litValue = 164.0740
    println("\n>> computed alpha_0 = $(outcome.alpha0) a.u.   (literature value = $litValue a.u., Puchalski et al.)")
    println(">> ratio computed/exact [Coulomb]   = $(outcome.alpha0.Coulomb/litValue)")
    println(">> ratio computed/exact [Babushkin] = $(outcome.alpha0.Babushkin/litValue)")
    #
end
