
println("Oa) Elastic scattering of electrons at a neutral atom: Dirac partial waves, differential cross section, " *
        "Sherman function and transport cross sections.")

setDefaults("print summary: open", "zzz-ParticleScattering.sum")
setDefaults("unit: energy", "eV")

grid = Radial.Grid(Radial.Grid(false), rnt = 4.0e-6, h = 5.0e-2, hp = 0.6e-2, rbox = 10.0)

if  true
    # Last visit:  17-Aug-2026
    # Last successful:  unknown ...
    # Elastic scattering of 300 eV electrons at the He 1s^2 ^1S_0 ground level, plane-wave projectile, static field
    # with a local exchange term.  This is the case that can be compared with a reference: the NIST Electron
    # Elastic-Scattering Cross-Section Database (SRD 64) is generated by ELSEPA, whose Dirac partial-wave treatment
    # this branch reproduces with JAC's own DFS density in place of ELSEPA's tabulated Dirac-Fock one.
    #
    # NOTE:  the comparison has NOT been carried out yet, so no date is claimed.  What IS established is the internal
    #        consistency: the total elastic cross section computed by quadrature of |f|^2 + |g|^2 over the scattering
    #        angle agrees with the partial-wave sum 4pi/k^2 SUM (l+1) sin^2 d^- + l sin^2 d^+ to ~14 digits, and the
    #        Sherman function is bounded by unity and vanishes in the forward direction.
    thetas     = [t for t in 0.05 : (pi/12) : pi]
    psSettings = ParticleScattering.Settings(ParticleScattering.Settings(),
                                             projectile     = ParticleScattering.Electron(),
                                             process        = ParticleScattering.ElasticScattering(),
                                             interaction    = ParticleScattering.StaticFieldFurnessMcCarthy(),
                                             beamType       = Beam.PlaneWave(),
                                             impactEnergies = [300.0], polarThetas = thetas, polarPhis = [0.0],
                                             printBefore    = true, epsPartialWave = 1.0e-6, maxL = 80)

    wc = Atomic.Computation(Atomic.Computation(), name="Elastic electron scattering at He", grid=grid,
                            nuclearModel    = Nuclear.Model(2.0),
                            initialConfigs  = [Configuration("1s^2")],
                            finalConfigs    = [Configuration("1s^2")],
                            processSettings = psSettings )

    wd = perform(wc; output=true)
    we = ParticleScattering.extractCrossSections(wd["particle-scattering events:"], 300.0, 0.0)
    #
elseif  false
    # Last successful:  unknown ...
    #
end
#
setDefaults("print summary: close", "")
